# Generated by Django 3.2.3 on 2021-05-21 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('favoritesApp', '0002_book_favorites'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='user',
            new_name='uploaded_by_id',
        ),
    ]
